sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t haritejnarayan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true haritejnarayan/docker-react npm run test